const fs=require('fs'),path=require('path');const out='ivdr-comparison';
const read=p=>fs.readFileSync(p,'utf8'),write=(p,s)=>{const file=path.join(out,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof s==='string'||Buffer.isBuffer(s)?s:JSON.stringify(s,null,2));};
write('package.json',{name:'ivdr-comparison-powerbi',version:'1.0.0',private:true,scripts:{test:'node ../ivdr-test.cjs',package:'pbiviz package'},dependencies:{'powerbi-visuals-api':'5.11.0'},devDependencies:{npm:'11.6.0','powerbi-visuals-tools':'7.2.1',typescript:'5.9.3','@playwright/test':'1.55.1',esbuild:'0.25.10'}});
write('pbiviz.json',{visual:{name:'ivdrOverview',displayName:'IVDR Registration Overview',guid:'ivdrOverviewB40D9D8A732A4D4EB34A485A92D0386B',visualClassName:'Visual',version:'1.0.0.0',description:'Site-level IVDR and Non-IVDR comparison with dispatch progress.',supportUrl:'https://github.com/DangerMitch2000/regulatory-timeline-demo/issues',gitHubUrl:'https://github.com/DangerMitch2000/regulatory-timeline-demo'},apiVersion:'5.11.0',author:{name:'Dualta Mitchell',email:'dualtamitchell@gmail.com'},assets:{icon:'assets/icon.png'},externalJS:null,style:'style/visual.less',capabilities:'capabilities.json',dependencies:null,stringResources:[]});
const roles=['SubID','OriginalDispatch','LatestDispatch','ActualDispatch','ActualSubmission','ActualApproval','Site','BusinessUnit','Project'];write('capabilities.json',{privileges:[],dataRoles:roles.map(name=>({name,displayName:name,kind:'Grouping'})),dataViewMappings:[{conditions:[Object.fromEntries(roles.map(n=>[n,{max:1}]))],table:{rows:{select:roles.map(role=>({for:{in:role}})),dataReductionAlgorithm:{window:{count:30000}}}}}],objects:{},supportsHighlight:false,supportsKeyboardFocus:true,supportsEmptyDataView:true});
write('tsconfig.json',{compilerOptions:{allowJs:true,checkJs:false,allowSyntheticDefaultImports:true,esModuleInterop:true,target:'es2022',module:'esnext',moduleResolution:'node',sourceMap:true,outDir:'./.tmp/build',declaration:false,skipLibCheck:true,lib:['es2022','dom']},files:['src/visual.ts']});
write('src/ivdr-roadmap.logic.js',read('ivdr-roadmap.logic.js'));write('src/ivdr-comparison.logic.js',read('ivdr-comparison.logic.js'));write('src/ivdr-comparison.ui.js',read('ivdr-comparison.ui.js'));write('style/visual.less',read('ivdr-comparison.css'));
write('src/visual.ts',`import powerbi from 'powerbi-visuals-api';
import {mapTable,viewingDay} from './ivdr-comparison.logic';
import {render} from './ivdr-comparison.ui';
import '../style/visual.less';
export class Visual implements powerbi.extensibility.visual.IVisual {
 private root:HTMLElement;private host:powerbi.extensibility.visual.IVisualHost;private rows:any[]=[];private notice='Add SubID and dispatch date fields.';private timer:any;private day:number;private state:any={businessUnit:"*",site:"*",month:-1,classification:"*",includeInferred:false};private projectMapped=false;private expanded=new Set<string>();
 constructor(o:powerbi.extensibility.visual.VisualConstructorOptions){this.host=o.host;this.root=document.createElement('div');o.element.append(this.root);this.day=viewingDay();this.timer=setInterval(()=>{const next=viewingDay();if(next!==this.day){this.day=next;this.draw();}},60000);}
 private draw(){render(this.root,this.rows,{notice:this.notice,projectMapped:this.projectMapped,state:this.state,expanded:this.expanded,onChange:(patch:any)=>{this.state={...this.state,...patch};this.draw();},onExpansion:(key:string)=>{if(this.expanded.has(key))this.expanded.delete(key);else this.expanded.add(key);this.draw();}});}
 public update(o:powerbi.extensibility.visual.VisualUpdateOptions):void{this.host.eventService?.renderingStarted(o);try{
 this.root.style.width=o.viewport.width+'px';this.root.style.height=o.viewport.height+'px';
 if(o.dataViews?.[0] || (o.type & 2)){const dv=o.dataViews?.[0],mapped=mapTable(dv?.table);this.rows=mapped.missing?[]:mapped.rows;this.projectMapped=!mapped.missingProject;this.notice=mapped.missing?'Add the SubID field. Dispatch dates are optional, but required to establish a chart month.':'';if(dv?.metadata?.segment){this.notice='Loading more data — counts currently reflect delivered rows only.';if(!this.host.fetchMoreData(true))this.notice='Power BI limited the delivered rows. Narrow report filters; all counts reflect delivered rows only.';}}
 this.day=viewingDay();this.draw();this.host.eventService?.renderingFinished(o);
 }catch(e){this.root.textContent='Unable to render: '+e.message;this.host.eventService?.renderingFailed(o,e.message);}}
 public getFormattingModel():powerbi.visuals.FormattingModel{return {cards:[]};}
 public destroy(){clearInterval(this.timer);this.root.remove();}
}
`);
write('README.md',read('ivdr-comparison.README.md'));
// Original neutral chart icon, with no work or third-party branding.
const zlib=require('zlib');function crc(b){let c=0xffffffff;for(const a of b){c^=a;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}function chunk(t,b){const a=Buffer.from(t),n=Buffer.alloc(4),c=Buffer.alloc(4);n.writeUInt32BE(b.length);c.writeUInt32BE(crc(Buffer.concat([a,b])));return Buffer.concat([n,a,b,c]);}const ih=Buffer.alloc(13);ih.writeUInt32BE(20);ih.writeUInt32BE(20,4);ih[8]=8;ih[9]=6;const px=Buffer.alloc(1620);for(let y=0;y<20;y++)for(let x=0;x<20;x++){let rgb=[255,255,255,255];if(x>=3&&x<7&&y>9&&y<18)rgb=[40,117,217,255];if(x>=8&&x<12&&y>5&&y<18)rgb=[237,146,45,255];if(x>=13&&x<17&&y>2&&y<18)rgb=[38,153,104,255];px.set(rgb,y*81+1+x*4);}write('assets/icon.png',Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ih),chunk('IDAT',zlib.deflateSync(px)),chunk('IEND',Buffer.alloc(0))]));
