import {collect,selectPage,dateRoles} from './key-submissions.logic.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const fmt=n=>n===null?'Not provided':new Date(n).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const joined=a=>a.length?a.join('; '):'Not provided';
const short=a=>a.length?(a[0]+(a.length>1?' +'+(a.length-1):'')):'Not provided';
const color=s=>/^(completed|approved|ha received)$/i.test(s)?'green':/^(in progress|sent to health authority|distributed|ready for submission)$/i.test(s)?'blue':/^(deferred|on hold.*)$/i.test(s)?'amber':/^(rejected|withdrawn|inactive)$/i.test(s)?'red':'grey';
export function render(root,rows,{state={query:'',page:0,selected:null},onChange=(patch)=>{},missing=[],notice='',synthetic=false}={}){
 root.replaceChildren();root.className='keyView';const header=el('header'),title=el('div');title.append(el('h1','Key Submissions — 2026'),el('p','ID business unit · Dispatch year 2026','scope'));header.append(title);root.append(header);
 if(synthetic)root.append(el('p','Fictional demonstration data','demo'));
 if(notice)root.append(el('p',notice,'notice'));if(missing.length){root.append(el('p','Add '+missing.join(', ')+' to show the correct key submissions.','notice'));return;}
 const result=collect(rows),view=selectPage(result.records,state);const tally=el('strong',result.records.length+' key submissions','tally');header.append(tally);
 const controls=el('div',undefined,'controls'),search=el('input');search.type='search';search.placeholder='Search product, country or submission';search.value=state.query||'';search.setAttribute('aria-label','Search key submissions');search.oninput=()=>onChange({query:search.value,page:0,selected:null});controls.append(search);root.append(controls);
 const wrap=el('div',undefined,'tableWrap'),table=el('table'),head=el('tr');['Submission / Product','Country','Next milestone'].forEach(t=>head.append(el('th',t)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');
 view.rows.forEach(r=>{const tr=el('tr'),main=el('td'),button=el('button',r.id,'record'),dot=el('span',undefined,'dot '+color(r.status));dot.title=r.status;dot.setAttribute('aria-label','Status: '+r.status);button.onclick=()=>onChange({selected:r.id});button.setAttribute('aria-label','Details for '+r.id);main.append(dot,button,el('span',short(r.products),'product'));main.title=joined(r.products)+'\nStatus: '+r.status;
 const country=el('td',short(r.countries),'country');country.title=joined(r.countries);const next=el('td',undefined,'milestone');next.append(el('span',r.next),el('strong',fmt(r.target)));next.title=r.next+' — '+fmt(r.target)+(r.issues.length?'\nDate issues: '+r.issues.join(', '):'');tr.append(main,country,next);body.append(tr)});table.append(body);wrap.append(table);root.append(wrap);
 if(!view.rows.length)root.append(el('p',result.records.length?'No key submissions match this search.':'No dated key submissions match ID and dispatch year 2026.','empty'));
 const footer=el('footer'),prev=el('button','‹ Previous'),next=el('button','Next ›');prev.disabled=view.page===0;next.disabled=view.page===view.pages-1;prev.onclick=()=>onChange({page:view.page-1,selected:null});next.onclick=()=>onChange({page:view.page+1,selected:null});footer.append(prev,el('span',view.matches.length?((view.page*10+1)+'–'+(view.page*10+view.rows.length)+' of '+view.matches.length):'0 matches'),next);root.append(footer);
 const checks=el('details',undefined,'checks');checks.append(el('summary','Scope and data checks'),el('p','Only Key Submission records in ID. One row per submission. Year uses actual dispatch, then latest planned dispatch, then original plan. Pending milestones sort by target date; missing targets last, followed by approved records.'));
 checks.append(el('p',result.undated.length+' without a dispatch date · '+result.excluded.length+' excluded for dispatch date issues · '+result.outside.length+' outside 2026 · '+result.unidentified+' key ID rows without a submission ID.'));
 const issueList=el('ul');result.excluded.forEach(x=>issueList.append(el('li',x.id+': '+x.reason)));result.undated.forEach(id=>issueList.append(el('li',id+': no dispatch date')));checks.append(issueList);root.append(checks);
 const record=result.records.find(r=>r.id===state.selected);if(record){const panel=el('section',undefined,'detailPanel');panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Submission details');const close=el('button','Close details','close');close.onclick=()=>onChange({selected:null});panel.append(close,el('h2',record.id),el('p',record.status,'status '+color(record.status)));const dl=el('dl');const entries=[['Regulatory objectives',joined(record.ros)],['Products',joined(record.products)],['Countries',joined(record.countries)],['Sites',joined(record.sites)],['Business unit','ID'],['Key flag','Key Submission'],['Next milestone',record.next+' · '+fmt(record.target)],['2026 scope',record.scopeSource+' · '+fmt(record.scopeDate)],...dateRoles.map(k=>[k.replace(/([a-z])([A-Z])/g,'$1 $2'),record.dates[k].issue?'Conflicting or invalid values':fmt(record.dates[k].value)])];entries.forEach(([k,v])=>dl.append(el('dt',k),el('dd',v)));panel.append(dl);root.append(panel);close.focus?.();}
 return view;
}
