const fs=require('fs');const base='roadmap-2026/verify/';fs.mkdirSync(base,{recursive:true});
fs.writeFileSync(base+'harness.ts',`import {Visual} from '../src/visual';import {roles} from '../src/roadmap-2026.logic';
const year=new Date().getFullYear(),rows=Array.from({length:72},(_,i)=>({SubID:'DEMO-'+i,OriginalDispatch:year+'-'+String(i%12+1).padStart(2,'0')+'-12',ActualDispatch:i%3===0?year+'-'+String(i%12+1).padStart(2,'0')+'-14':null,ActualSubmission:i%4===1?year+'-06-01':null,Site:['North','South','West','East','Central','Coastal',null][i%7],BusinessUnit:['ID','CMI','CSP','TOX'][i%4]}));rows.push({SubID:'UNDATED',ActualSubmission:year+'-01-01',BusinessUnit:'ID'} as any);
const host={eventService:{renderingStarted(){},renderingFinished(){document.body.dataset.ready='true'},renderingFailed(o,e){throw Error(e)}},fetchMoreData(){return false}};
const visual=new Visual({element:document.getElementById('host'),host} as any);const send=(data=rows,segment=false)=>visual.update({type:2,viewport:{width:1320,height:850},dataViews:[{metadata:segment?{segment:{}}:{},table:{columns:roles.map(role=>({roles:{[role]:true}})),rows:data.map(r=>roles.map(k=>r[k]))}}]} as any);send();
document.getElementById('resize').onclick=()=>visual.update({type:4,viewport:{width:650,height:850}} as any);document.getElementById('reset').onclick=()=>send();document.getElementById('filter').onclick=()=>send(rows.slice(0,8));document.getElementById('empty').onclick=()=>send([]);document.getElementById('partial').onclick=()=>send(rows,true);
`);
fs.writeFileSync(base+'index.html',`<!doctype html><html><head><meta charset="utf-8"><title>Roadmap local review — synthetic data</title><link rel="stylesheet" href="harness.css"><style>body{margin:20px;background:#edf2f7;font:14px Segoe UI}body>p{color:#526377}#host{width:max-content;border:1px solid #d8e1ec;border-radius:8px;overflow:hidden}body>button{margin:10px;padding:8px}</style></head><body><p>LOCAL REVIEW · Synthetic demonstration data · Not published</p><div id="host"></div><button id="resize">Narrow visual</button><button id="reset">Reset host data / width</button><button id="filter">Report filter test</button><button id="empty">Empty data test</button><button id="partial">Partial data test</button><script src="harness.js"></script></body></html>`);
fs.writeFileSync(base+'run.cjs',`const {chromium}=require('@playwright/test'),assert=require('assert/strict'),http=require('http'),fs=require('fs'),path=require('path');
(async()=>{const server=http.createServer((req,res)=>{const p=path.join(__dirname,new URL(req.url,'http://localhost').pathname);fs.readFile(p,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(b);});}).listen(8772,'127.0.0.1');const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1400,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await page.goto('http://127.0.0.1:8772/index.html');await page.waitForSelector('body[data-ready=true]');assert.equal(await page.locator('h1').innerText(),new Date().getFullYear()+' Roadmap');assert.match(await page.locator('.average').innerText(),/72 ÷ 12/);assert.match(await page.locator('.cleanup').innerText(),/: 1$/);
const main=await page.locator('.layout > section').first().boundingBox(),side=await page.locator('.sites').boundingBox();assert.ok(side.x>main.x+main.width);
await page.getByRole('checkbox',{name:'Include inferred dispatches'}).check();assert.match(await page.locator('.average').innerText(),/72 ÷ 12/);await page.getByRole('combobox',{name:'Business unit'}).selectOption('"ID"');assert.match(await page.locator('.average').innerText(),/18 ÷ 12/);await page.locator('.sites button').first().click();assert.equal(await page.locator('.monthRow').count(),12);
await page.locator('#resize').click();assert.equal(await page.getByRole('checkbox').isChecked(),true);assert.equal(await page.getByRole('combobox').inputValue(),'"ID"');assert.equal(await page.locator('.monthRow').count(),12);assert.ok((await page.locator('.sites').boundingBox()).y>(await page.locator('.chart').boundingBox()).y);
await page.locator('#reset').click();await page.getByRole('combobox').selectOption('*');await page.screenshot({path:path.join(__dirname,'roadmap-preview.png'),fullPage:true});
await page.getByRole('button',{name:'Screenshot mode',exact:true}).click();assert.equal(await page.getByRole('combobox').count(),0);assert.ok(await page.locator('.slideCapture').count());const slide=page.locator('.slideCapture svg');const before=await slide.textContent();const full=await slide.evaluate(s=>s.getScreenCTM().a);await page.locator('#resize').click();const small=await slide.evaluate(s=>s.getScreenCTM().a);assert.ok(small<full);assert.equal(await slide.textContent(),before);assert.ok(await slide.locator('text').first().evaluate(t=>t.getBoundingClientRect().height)>16);await slide.screenshot({path:path.join(__dirname,'roadmap-preview-small.png')});await page.locator('#reset').click();await slide.screenshot({path:path.join(__dirname,'roadmap-preview.png')});await page.locator('.slideCapture').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('.slideCapture').count(),0);assert.ok(await page.getByRole('combobox').count());await page.locator('svg rect[tabindex]').first().hover();assert.equal(await page.locator('.tip').isVisible(),true);await page.locator('#filter').click();assert.match(await page.locator('.average').innerText(),/8 ÷ 12/);await page.locator('#empty').click();assert.match(await page.locator('.average').innerText(),/0 ÷ 12/);await page.locator('#partial').click();assert.match(await page.locator('.notice').innerText(),/limited/);assert.deepEqual(errors,[]);console.log('PASS: actual Visual host, responsive right-site layout, native unit filter and inference, expansion, resize state persistence, tooltip, report filtering, empty/partial data, no browser errors.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});`);
