import {summarize,milestones} from './site-plan.logic.js';
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const svgEl=(tag,attrs={},text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;};
export function render(root,rows,{state={site:null,unit:'*',capture:false},onChange=(patch)=>{},missing=[],notice='',synthetic=false}={}){
 root.replaceChildren();root.className='sitePlan'+(state.capture?' capture':'');root.tabIndex=0;root.onkeydown=e=>{if(e.key==='Escape'&&state.capture)onChange({capture:false})};
 if(missing.length){root.append(el('p','Map the required fields: '+missing.join(', '),'notice'));return;}
 const r=summarize(rows,state),s=r.selected;const controls=el('div',undefined,'controls');
 function dropdown(label,key,options,value){const wrap=el('label',label),select=el('select');select.setAttribute('aria-label',label);if(!options.some(o=>o.value===value))options.push({value,label:(value??'None')+' (no matching records)'});options.forEach(o=>{const opt=el('option',o.label);opt.value=JSON.stringify(o.value);select.append(opt)});select.value=JSON.stringify(value);select.onchange=()=>onChange({[key]:JSON.parse(select.value)});wrap.append(select);controls.append(wrap);}
 dropdown('Site','site',r.choices.map(s=>({value:s.key,label:s.label})),s.key);dropdown('Business unit','unit',[{value:'*',label:'All business units'},...r.units.map(value=>({value,label:value??'Unassigned'}))],state.unit===undefined?'*':state.unit);const capture=el('button','Screenshot mode');capture.title='Hide controls. Press Escape to return.';capture.onclick=()=>{onChange({capture:true});root.focus?.()};controls.append(capture,el('span','Select a site, then use Screenshot mode. Escape returns to controls.','help'));root.append(controls);
 if(notice)root.append(el('p',notice,'notice'));
 const stage=el('div',undefined,'chartStage'),svg=svgEl('svg',{viewBox:'0 0 1000 370',preserveAspectRatio:'xMidYMid meet',role:'img','aria-label':'Site Regulatory Plan 2026 for '+s.label+'. Latest estimates and original plans for dispatches, submissions and approvals, H1 and H2.'});stage.append(svg);root.append(stage);
 const text=(x,y,value,size=25,fill='#163253',extra={})=>svg.append(svgEl('text',{x,y,'font-size':size,fill,...extra},value));
 text(18,37,'Site Regulatory Plan · 2026',34,'#142c4e',{'font-weight':650});const siteText=s.label.length>43?s.label.slice(0,40)+'…':s.label;text(18,73,siteText+(state.unit&&state.unit!=='*'?' · '+state.unit:''),26);svg.append(svgEl('title',{},'Site: '+s.label+'; Business unit: '+(state.unit==='*'?'All':state.unit??'Unassigned')));
 svg.append(svgEl('rect',{x:660,y:16,width:35,height:18,fill:'#466be0'}));text(706,32,'Latest estimate',21);svg.append(svgEl('rect',{x:660,y:51,width:35,height:20,fill:'none',stroke:'#748196','stroke-width':2}));text(706,69,'Original plan',21);
 const colors=['#5862c7','#2486d8','#179c89'],starts=[207,644],plotWidth=266;
 ['H1 · Jan–Jun','H2 · Jul–Dec'].forEach((label,h)=>{const x=starts[h];text(x,116,label,26,'#163253',{'font-weight':650});[0,.5,1].forEach(f=>{const px=x+plotWidth*f;svg.append(svgEl('line',{x1:px,x2:px,y1:131,y2:303,stroke:'#e0e6ef','stroke-width':1.3}));text(px,328,String(r.axisMax*f),21,'#64748a',{'text-anchor':'middle'});});
  milestones.forEach((label,i)=>{const y=156+i*62,c=s.counts[h][i];if(h===0)text(18,y+8,label,27);const outline=svgEl('rect',{x,y:y-22,width:c.original/r.axisMax*plotWidth,height:42,fill:'none',stroke:'#78879a','stroke-width':2}),bar=svgEl('rect',{x,y:y-14,width:c.latest/r.axisMax*plotWidth,height:26,fill:colors[i]});svg.append(outline,bar);text(x+Math.max(c.latest,c.original)/r.axisMax*plotWidth+8,y+8,String(c.latest),27,colors[i],{'font-weight':700});const hit=svgEl('rect',{x,y:y-24,width:plotWidth+60,height:48,fill:'transparent',tabindex:0});hit.append(svgEl('title',{},s.label+' · '+label+' · '+['Jan–Jun','Jul–Dec'][h]+' 2026\nLatest estimate: '+c.latest+'\nOriginal plan: '+c.original));svg.append(hit);});
 });
 const notes=[];if(synthetic)notes.push('Illustrative data');if(!s.records)notes.push('No matching records');if(s.issues.length)notes.push(s.issues.length+' date issues');if(s.missing)notes.push(s.missing+' missing plan dates');if(r.missingIds)notes.push(r.missingIds+' rows missing IDs');if(s.fallback)notes.push('Latest uses original where blank');if(!notes.length)notes.push('Counts by planned milestone date');text(18,362,notes.join(' · '),18,'#68768a');
 if(!state.capture){const checks=el('details',undefined,'checks');checks.append(el('summary','Date rules and data checks'),el('p','Fixed to 2026. Each submission counts once per milestone and plan. Milestones use their own planned dates. Blank latest dates fall back to original; invalid or conflicting latest dates never fall back. Actual completion dates are not used. Both halves and every site share one scale within the selected business unit.'));
 checks.append(el('p',s.records+' distinct submissions at this site; '+s.fallback+' milestone estimates use their original date; '+s.missing+' milestones have neither plan; '+s.issues.length+' milestone date issues. Multiple-site submissions are kept in one unallocated bucket.'));
 const list=el('ul');s.issues.forEach(x=>list.append(el('li',x.id+' · '+x.fields.join(', '))));checks.append(list);root.append(checks);}
 return r;
}
